apiVersion: v1
data:
  JAVA_TOOLS_OPTIONS: -XX:+ExitOnOutOfMemoryError -Xmx480M
  TZ: Europe/Oslo
  fint.consumer.org-id: fintlabs.no
  fint.kafka.topic.org-id: fintlabs.no
  fint.relations.default-base-url: https://beta.felleskomponent.no
  spring.kafka.consumer.group-id: consumer-utdanning-vurdering-beta
  spring.webflux.base-path: /utdanning/vurdering
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: fint-core-consumer-utdanning-vurdering_fintlabs-no
    app.kubernetes.io/name: fint-core-consumer-utdanning-vurdering
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: fintlabs.no
    fintlabs.no/team: core
  name: fint-core-consumer-utdanning-vurdering
  namespace: fintlabs-no
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: fint-core-consumer-utdanning-vurdering_fintlabs-no
    app.kubernetes.io/name: fint-core-consumer-utdanning-vurdering
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: fintlabs.no
    fintlabs.no/team: core
  name: fint-core-consumer-utdanning-vurdering
  namespace: fintlabs-no
spec:
  ports:
  - port: 8080
  selector:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: fint-core-consumer-utdanning-vurdering_fintlabs-no
    app.kubernetes.io/name: fint-core-consumer-utdanning-vurdering
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: fintlabs.no
    fintlabs.no/team: core
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: fint-core-consumer-utdanning-vurdering_fintlabs-no
    app.kubernetes.io/name: fint-core-consumer-utdanning-vurdering
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: fintlabs.no
    fintlabs.no/team: core
  name: fint-core-consumer-utdanning-vurdering
  namespace: fintlabs-no
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: fint-core-consumer-utdanning-vurdering_fintlabs-no
      app.kubernetes.io/name: fint-core-consumer-utdanning-vurdering
      app.kubernetes.io/part-of: fint-core
      app.kubernetes.io/version: latest
      fintlabs.no/org-id: fintlabs.no
      fintlabs.no/team: core
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/path: utdanning/vurdering/actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: fint-core-consumer-utdanning-vurdering_fintlabs-no
        app.kubernetes.io/name: fint-core-consumer-utdanning-vurdering
        app.kubernetes.io/part-of: fint-core
        app.kubernetes.io/version: latest
        fintlabs.no/org-id: fintlabs.no
        fintlabs.no/team: core
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: fint-core-consumer-utdanning-vurdering-kafka
        - configMapRef:
            name: fint-core-consumer-utdanning-vurdering
        image: ghcr.io/fintlabs/fint-core-consumer-utdanning-vurdering:sha-0000000
        name: fint-core-consumer-utdanning-vurdering
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 1152Mi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /credentials
          name: credentials
      restartPolicy: Always
      volumes:
      - name: credentials
        secret:
          secretName: fint-core-consumer-utdanning-vurdering-kafka-certificates
---
apiVersion: fintlabs.no/v1alpha1
kind: KafkaUserAndAcl
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: fint-core-consumer-utdanning-vurdering_fintlabs-no
    app.kubernetes.io/name: fint-core-consumer-utdanning-vurdering
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: fintlabs.no
    fintlabs.no/team: core
  name: fint-core-consumer-utdanning-vurdering
  namespace: fintlabs-no
spec:
  acls:
  - permission: admin
    topic: fintlabs-no.fint-core.*
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: fint-core-consumer-utdanning-vurdering_fintlabs-no
    app.kubernetes.io/name: fint-core-consumer-utdanning-vurdering
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: fintlabs.no
    fintlabs.no/team: core
  name: fint-core-consumer-utdanning-vurdering
  namespace: fintlabs-no
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`beta.felleskomponent.no`) && (PathPrefix( `/utdanning/vurdering/fravar`)
      || PathPrefix( `/utdanning/vurdering/elevfravar`) || PathPrefix( `/utdanning/vurdering/fravarsoversikt`)
      || Path(`/utdanning/vurdering/admin/status`)) && Headers(`x-org-id`, `fintlabs.no`)
    services:
    - name: fint-core-consumer-utdanning-vurdering
      port: 8080
