spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  kafka:
    consumer:
      group-id: consumer-utdanning-vurdering

fint:
  kafka:
    application-id: consumer-utdanning-vurdering
    enable-ssl: true
logging:
  level:
    root: INFO
    #org.apache.kafka: DEBUG