server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  webflux:
    base-path: /utdanning/vurdering
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumer
  codec:
    max-in-memory-size: 200MB
    consumer:
      group-id: # consumer-utdanning-vurdering-<your-instance-id>

fint:
  consumer:
    org-id: fintlabs.no
    domain: utdanning
    package: vurdering
  kafka:
    application-id: consumer-utdanning-vurdering
    enable-ssl: false
    default-replicas: 1
    topic:
      org-id: fintlabs.no
      domain-context: fint-core

logging:
  level:
    no.fintlabs.kafka: WARN
    root: INFO
    org:
      apache.kafka: WARN
      springframework:
        kafka: WARN
        security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus