name: CD

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Select and environment'
        required: true
        default: 'warning'
        type: choice
        options:
          - aks-alpha-fint-2021-11-18
          - aks-beta-fint-2021-11-23
          - aks-api-fint-2022-02-08
      org:
        description: 'Select organisation'
        required: true
        default: 'warning'
        type: choice
        options:
          - fintlabs-no
          - viken-no
          - visma-com
#          - vlfk-no
#          - rogfk-no
#          - vtfk-no
#          - trondelagfk-no
#          - innlandet-no
#          - agderfk-no

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CLUSTER_NAME: ${{ inputs.cluster }}
  ORG: ${{ inputs.org }}

jobs:
  cd:
    name: deploy for ${{ matrix.org }} to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Get resource group name
        uses: actions/github-script@v6
        id: rg
        with:
          script: |
            const a = '${{ env.CLUSTER_NAME }}'.split('-')
            return `rg-${a[0]}-${a[1]}`
          result-encoding: string

      - name: Get environment
        uses: actions/github-script@v6
        id: environment
        with:
          script: return '${{ matrix.cluster }}'.split('-')[1]
          result-encoding: string

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4.3.0
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha,enable=true,priority=100,prefix=shaF-,suffix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Bake manifests with Kustomize
        uses: azure/k8s-bake@v2.4
        with:
          renderEngine: 'kustomize'
          kustomizationPath: 'kustomize/overlays/${{ steps.environment.outputs.result }}/${{ env.ORG}}'
        id: bake

      - name: Set the target cluster
        uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets[format('AKS_{0}_FINT_GITHUB', steps.environment.outputs.result)] }}"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ steps.rg.outputs.result }}

      - name: Deploy to ${{ env.CLUSTER_NAME }}
        uses: azure/k8s-deploy@v4.4
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ steps.meta.outputs.tags }}
          namespace: ${{ env.ORG }}
          action: deploy