name: deploy-to-kubernetes
on:
  push:
    branches: ['CT-523-legg-til-kustomize', 'main']

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ALPHA:

jobs:
  deploy-to-kubernetes:
    name: deploy to ${{ matrix.org }} in ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        org: [viken-no]
        cluster:
          - aks-alpha-fint-2021-11-18
          - aks-beta-fint-2021-11-23
#          - aks-api-fint-2022-02-08
#          - aks-pwf-fint-2021-10-20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - uses: actions/github-script@v6
        name: Get resource group name
        id: rg
        with:
          script: |
            const a = '${{ matrix.cluster }}'.split('-')
            return `rg-${a[0]}-${a[1]}`
          result-encoding: string

      - uses: actions/github-script@v6
        name: Get environment
        id: environment
        with:
          script: |
            const a = '${{ matrix.cluster }}'.split('-')
            return `${a[1]}`
          result-encoding: string

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha,enable=true,priority=100,prefix=shaF-,suffix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Bake manifests with Kustomize
        id: bake
        uses: azure/k8s-bake@v2.4
        with:
          renderEngine: 'kustomize'
          kustomizationPath: 'kustomize/overlays/${{ steps.environment.outputs.result }}/${{ matrix.org }}'

      - name: Set the target cluster
        uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets[format('AKS_{0}_FINT_GITHUB', steps.environment.outputs.result)] }}"
          cluster-name: ${{ matrix.cluster }}
          resource-group: ${{ steps.rg.outputs.result }}

      - name: Deploy
        uses: azure/k8s-deploy@v4.9
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ steps.meta.outputs.tags }}
          namespace: ${{ matrix.org }}
          action: deploy
